[package]
name = "typst-project-archiver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
regex = "1.11.1"
toml = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
walkdir = "2.5.0"
