[package]
name = "typst-project-to-go"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
regex = "1.11.1"
sha2 = "0.10.9"
thiserror = "2.0.12"
toml = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
walkdir = "2.5.0"
