jobs:
  - title: "Senior Security Consultant"
    company:
      en: "Black Duck / Synopsys GmbH (Germany)"
      de: "Black Duck / Synopsys GmbH (Deutschland)"
    period: 
      en: "Oct/2021–present (3 years 9 months)"
      de: "Okt/2021–aktuell (3 Jahre 9 Monate)"
    description: 
      en: >
         #v(-0.6em)#text(fill: subdue_color, size: 0.8em)[_The Synopsys Software Integrity Group became a standalone company, Black Duck, in October 2024._]


         Information security consulting, mainly around threat modeling. Development of internal capabilities and external perception. Examples:

         - Product Owner role for a threat modeling automation tool. 

         - Development of the threat modeling methodology.

         - Creation of training material (threat modeling, secure Java development, among others).

         - Lead customer trainings (in person and virtual).

         - Maintain templates for project deliverables (e.g. reports, diagrams).

         - SME in Post-Quantum Cryptography (PQC).

         - Represent the company in public with whitepapers, participation in conferences and responding to journalistic inquiries. 
      de: > 
        #v(-0.6em)#text(fill: subdue_color,size: 0.8em)[Die _Synopsys Software Integrity Group_ wurde im Oktober 2024 eigenständig unter dem Namen "Black Duck".] 


        IT-Security Beratung, vor allem zum Thema _Threat Modeling_. Entwicklung der internen Kapazitäten und deren externe Wahrnehmung. Beispiele: 
        
        - Product Owner für ein Tool für die Automatisierung von Threat Models. 

        - Weiterentwicklung der Threat Modeling Methodik.

        - Durchführung von virtuellen und Präsenztrainings (intern und für Kunden).

        - Weiterentwicklung und Betreuung des externen Trainingangebots (u.a. zu Threat Modeling, sichere Entwicklung in Java).

        - Erstellung und Wartung von Templates für Liefergegenstände (Eng: _deliverables_) wie Berichte und Diagramme.

        - Firmenexperte (Eng: SME) in Post-Quantum Kryptographie (Eng: PQC).

        - Äußerliche Representation der Firma durch Publikationen, Konferenzen, Webinars und bei der Beantwortung von Fragen von Journalisten. 
  # - title: "Security Consultant"
  #   company: "Synopsys GmbH (Deutschland)"
  #   period: "Oct/2021–Feb/2023 (1 Jahre 4 Monate)"
  #   description: " Durchführung und Ermöglichung von Beratungsprojekte im Bereich Security, vor allem um das Thema _Threat Modeling_. Erstellung und Wartung von Templates für Berichte und Diagramme."
  - title: "Security Consultant"
    company: 
      en: ESCRYPT GmbH (Germany)
      de: "ESCRYPT GmbH (Deutschland)"
    period: 
      en: "Feb/2017–Sep/2021 (4 years 7 months)"
      de: "Feb/2017–Sep/2021 (4 Jahre 7 Monate)"
    description: 
      en: "Consult on security projects for embedded device OEMs, mainly in the automotive and IoT domains. Risk analyses, security concepts, development and maintenance of LaTeX templates."
      de: "IT-Security Beratung für Hersteller und Lieferanten von _embedded_ Geräten (v.a. Automobil-Branche und IoT). Beispiele: Bedrohungsanalyse, Sicherheitskonzepte, Weiterentwicklung von Templates (LaTeX)."
  - title: "Information Security Consultant"
    company: "Cybertech de Colombia"
    period: 
      en: "Dec/2011–Aug/2014 (2 years 8 months)"
      de: "Dez/2011–Aug/2014 (2 Jahre 8 Monate)"
    description: 
      en: >
        Security consulting with emphasis on cryptography. 

        - Development, installation and support of cryptographic software.

        - Prepare and hold trainings (e.g. cryptography, secure coding).

        - Assist customers with bespoke security needs.
      de: > 
        IT-Security Beratung mit Schwerpunkt Kryptographie. 

        - Entwicklung, Einrichtung und Support von kryptographischer Software.
        
        - Planung und Durchführung von Trainings (Beispiele: Kryptographie, sichere Softwareentwicklung). 

        - Maßgeschneiderte Dienstleistungen rund um IT-Security.
  - title: 
      en: "(Internship) Developer"
      de: "(Praktikum) Softwareentwickler"
    company: "Indra Colombia"
    period: 
      en: "Jul/2010–Jan/2011 (6 months)"
      de: "Jul/2010–Jan/2011 (6 Monate)"
    description: 
      en: Develop and support software for a telco.
      de: "Entwicklung und Support von Software im Telekommunkationsbereich."